<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\InvoiceCapture.Application\InvoiceCapture.Application.csproj" />
    <ProjectReference Include="..\InvoiceCapture.Infrastructure\InvoiceCapture.Infrastructure.csproj" />
    <ProjectReference Include="..\InvoiceCapture.Contracts\InvoiceCapture.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\specs\ComarchInvoice\*.xsd" Link="specs\ComarchInvoice\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
