<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\InvoiceCapture.Domain\InvoiceCapture.Domain.csproj" />
    <ProjectReference Include="..\..\src\InvoiceCapture.Application\InvoiceCapture.Application.csproj" />
    <ProjectReference Include="..\..\src\InvoiceCapture.Infrastructure\InvoiceCapture.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\specs\ComarchInvoice\*.xsd" Link="specs\ComarchInvoice\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
